### ISSUE TITLE
Can't retrieve the status of the modem

### ISSUE THREAD

**Issue by goodbyepavlyi** [frimtec/compal-wifi-switch#25]
I am trying to retrieve the status using the command "compal-wifi-switch status --host 192.168.0.1 --password "REDACTED" --verbose", but here is the output.

`INFO:compal:302 [http://192.168.0.1/] => '../common_page/login.html' [token: 1905655552]
15
http://192.168.0.1/xml/setter.xml OrderedDict([('fun', 15), ('Username', 'admin'), ('Password', 'x3CtepmumR5Wj')])
b'successful;SID=877090304'
{'Access-Control-Allow-Origin': 'http://192.168.0.1', 'Referrer-Policy': 'origin', 'Content-Security-Policy': "default-src 'self' 'unsafe-eval' 'unsafe-inline'", 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Date': 'Thu, 08 Dec 2022 20:53:52 GMT', 'Last-Modified': 'Thu, 07 Apr 2022 07:19:41 GMT', 'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Expires': '-1', 'Content-Type': 'text/xml', 'Connection': 'close', 'Set-Cookie': 'sessionToken=2230701568; Domain=192.168.0.1; path=/; HttpOnly; Expires=Thu, 08 Dec 2022 21:03:52 GMT; '}
{'SID': ['877090304']} ['877090304'] successful;SID=877090304
INFO:compal:[login] SID 877090304
1
http://192.168.0.1/xml/getter.xml OrderedDict([('token', '2230701568'), ('fun', 1)])
b''
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\compal-wifi-switch.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\compal_wifi_switch\main.py", line 120, in main
    args.func(args)
  File "C:\Python311\Lib\site-packages\compal_wifi_switch\main.py", line 11, in status
    status_object = Commands.status(args.host, args.password)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\compal_wifi_switch\__init__.py", line 75, in status
    global_settings = etree.fromstring(modem.xml_getter(GetFunction.GLOBALSETTINGS, {}).content, parser=parser)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1`

**Comment by frimtec** [comment]
Hi, there are several possibilities:
a) Compal modems only allow one session at a time. Make sure you explicitly logout from the modems admin UI before executing compal-wifi-switch commands.
b) You suffer from the login issue mentioned here https://github.com/ties/compal_CH7465LG_py/issues/38 (fixed in the underlying communication layer but not supported in compal-wifi-switch as I have no modem of this version to test).
c) Your modems firmware version is not compatible with the underlying communication layer (https://github.com/ties/compal_CH7465LG_py).

Hope this helps to locate the cause of your login problems.
* Your modems firmware version is not supportet (https://github.com/ties/compal_CH7465LG_py/issues/38)

**Comment by goodbyepavlyi** [comment]
Hey, I think it's due to the reason B, though I can't really seem to understand how to change the `send_token` variable to False instead of True in the Home Assistant Integration.
